spring.application.name=todo
server.port=8080

spring.datasource.url=jdbc:h2:mem:todoApp

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=Deepi@123

spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=admin
spring.security.user.password=Deepi@123
